# Generated by Django 5.1.6 on 2025-05-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttier',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='investmenttier',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tier_logos/'),
        ),
    ]
