# Generated by Django 5.0.2 on 2025-06-09 17:30

from django.db import migrations
from django.utils import timezone

def populate_end_date(apps, schema_editor):
    """
    Populate the end_date for existing Investment records where it is null.
    """
    Investment = apps.get_model('core', 'Investment')
    for investment in Investment.objects.filter(end_date__isnull=True):
        if investment.start_date and investment.tier and investment.tier.duration_days is not None:
            investment.end_date = investment.start_date + timezone.timedelta(days=investment.tier.duration_days)
            investment.save(update_fields=['end_date'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(populate_end_date, reverse_code=migrations.RunPython.noop),
    ]
