# Generated by Django 5.1.6 on 2025-05-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_investmenttier_description_investmenttier_logo'),
    ]

    operations = [
    ]
