# Generated by Django 5.1.6 on 2025-05-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_auto_reinvest'),
        ('core', '0004_auto_20250523_2230'),
    ]

    operations = [
    ]
