# Generated by Django 5.1.6 on 2025-05-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_user_level_fields'),
        ('core', '0005_merge_0002_add_auto_reinvest_0004_auto_20250523_2230'),
    ]

    operations = [
    ]
