# Generated by Django 5.1.6 on 2025-05-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_withdrawal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='bank_details',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='account_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='branch_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
