# Generated by Django 5.1.6 on 2025-05-25 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_withdrawal_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('special_return_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.investmenttier')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
