# Generated by Django 5.1.6 on 2025-05-26 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_dailyspecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
