# Generated by Django 5.0.4 on 2025-06-05 13:50

from django.db import migrations

def update_investment_tiers(apps, schema_editor):
    InvestmentTier = apps.get_model('core', 'InvestmentTier')

    # --- Create New Level 2 Tiers ---

    # Booster Pack
    InvestmentTier.objects.update_or_create(
        name='Booster Pack',
        defaults={
            'min_level': 2,
            'amount': 250.00,
            'duration_days': 4,
            'return_amount': 550.00,
            'description': 'A fast-paced plan for Level 2 users to boost their returns.'
        }
    )

    # Momentum
    InvestmentTier.objects.update_or_create(
        name='Momentum',
        defaults={
            'min_level': 2,
            'amount': 750.00,
            'duration_days': 6,
            'return_amount': 1600.00,
            'description': 'Build momentum with this high-value return plan for Level 2 investors.'
        }
    )

    # --- Update Existing Silver Tier ---
    
    try:
        silver_tier = InvestmentTier.objects.get(name='Silver')
        silver_tier.return_amount = 3500.00  # Increasing return from 3000 to 3500
        silver_tier.min_level = 2 # Ensure it's level 2
        silver_tier.save()
    except InvestmentTier.DoesNotExist:
        # If it doesn't exist, create it as a Level 2 tier
        InvestmentTier.objects.create(
            name='Silver',
            min_level=2,
            amount=2000.00,
            duration_days=7,
            return_amount=3500.00,
            description='Silver investment plan with an enhanced return.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_adminactivitylog'),
    ]

    operations = [
        migrations.RunPython(update_investment_tiers),
    ]
