# Generated by Django 5.1.6 on 2025-06-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_voucher'),
    ]

    operations = [
    ]
