# Generated by Django 5.1.6 on 2025-05-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20250523_2236'),
        ('core', '0006_merge_user_fields'),
    ]

    operations = [
    ]
