# Generated by Django 5.1.6 on 2025-05-24 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_referral_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='auto_reinvest',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='bonus_paid',
        ),
        migrations.AddField(
            model_name='investmenttier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmenttier',
            name='min_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='investmenttier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='investmenttier',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='investmenttier',
            name='duration_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='investmenttier',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='investmenttier',
            name='return_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='referral',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
