# Generated by Django 5.1.6 on 2025-05-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_withdrawal_bank_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('ABSA', 'ABSA Bank'), ('CAPITEC', 'Capitec Bank'), ('FNB', 'First National Bank'), ('INVESTEC', 'Investec Bank'), ('NEDBANK', 'Nedbank'), ('STANDARD', 'Standard Bank'), ('AFRICAN', 'African Bank'), ('BIDVEST', 'Bidvest Bank'), ('DISCOVERY', 'Discovery Bank'), ('GRINDROD', 'Grindrod Bank'), ('HSBC', 'HSBC Bank'), ('MERCANTILE', 'Mercantile Bank'), ('SAHL', 'South African Home Loans'), ('TYM', 'TymeBank'), ('UBS', 'UBS Bank')], max_length=100),
        ),
    ]
